---
title: "STA302 Tutorial 2 - opendatatoronto"
author: "Ravnit Lotay"
format: html
---

#### Preamble ####
# Purpose: Analyze the Toronto Bicycle Thefts dataset, focusing on the trend of bicycle thefts in Toronto since 2012. 
# Author: Ravnit Lotay
# Email: ravnit.lotay@mail.utoronto.ca
# Date: 15 January 2024
# Prerequisites: Familiarity with R and access to the opendatatoronto library.

```{r}
# Load the necessary libraries
library(opendatatoronto)
library(dplyr)
library(ggplot2)

resources <- list_package_resources("c7d34d9b-23d2-44fe-8b3b-cd82c8b38978")

# Load the data and remove any empty values"
resource_id <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
data <- get_resource(resource_id)
data <- na.omit(data)

# Filter the data to years including and after 2012
data_filtered <- data %>%
  filter(OCC_YEAR >= 2012)

# Get the number of thefts per year
thefts_by_year <- data_filtered  %>%
  group_by(OCC_YEAR) %>%
  summarize(Count = n())

# Create the bar chart and add additional x-axis values
bar_chart <- ggplot(thefts_by_year, aes(x = OCC_YEAR, y = Count)) +
  geom_bar(stat = "identity", fill = "blue") +
  scale_x_continuous(breaks = seq(min(thefts_by_year$OCC_YEAR), max(thefts_by_year$OCC_YEAR), by = 1)) +
  labs(title = "Bicycle Thefts in Toronto by Year (2012 and onward)",
       x = "Year",
       y = "Number of Thefts") +
  theme_minimal()

# Print the bar chart
print(bar_chart)